-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.clinical_events
(
    id serial NOT NULL,
    patient_id integer NOT NULL,
    event_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    event_date date NOT NULL,
    value numeric(10, 2),
    notes text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT clinical_events_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.correction_logs
(
    id serial NOT NULL,
    patient_id integer NOT NULL,
    user_id integer NOT NULL,
    supervisor_id integer,
    hospital_number character varying(100) COLLATE pg_catalog."default" NOT NULL,
    field_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    old_value text COLLATE pg_catalog."default",
    new_value text COLLATE pg_catalog."default" NOT NULL,
    reason text COLLATE pg_catalog."default" NOT NULL,
    status character varying(50) COLLATE pg_catalog."default" DEFAULT 'pending'::character varying,
    approved_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT correction_logs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.radet_records
(
    id serial NOT NULL,
    cycle_id integer NOT NULL,
    hospital_number character varying(100) COLLATE pg_catalog."default" NOT NULL,
    date_of_birth date,
    sex character(1) COLLATE pg_catalog."default",
    art_start_date date,
    current_regimen character varying(100) COLLATE pg_catalog."default",
    last_drug_pickup date,
    last_vl_sample_date date,
    last_vl_result numeric(10, 2),
    last_vl_result_date date,
    last_clinic_visit date,
    is_active boolean DEFAULT true,
    is_on_art boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    months_of_arv_dispensed integer,
    CONSTRAINT radet_records_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.radet_upload_logs
(
    id serial NOT NULL,
    filename character varying COLLATE pg_catalog."default",
    cycle_id integer,
    records_added integer,
    records_updated integer,
    uploaded_by integer,
    upload_date timestamp without time zone,
    CONSTRAINT radet_upload_logs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    username character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    full_name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    role character varying(50) COLLATE pg_catalog."default" NOT NULL,
    facility character varying(200) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.validation_cycles
(
    id serial NOT NULL,
    name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    start_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    end_date timestamp without time zone,
    is_active boolean DEFAULT true,
    description text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT validation_cycles_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.validation_results
(
    id serial NOT NULL,
    cycle_id integer NOT NULL,
    patient_id integer NOT NULL,
    user_id integer NOT NULL,
    hospital_number character varying(100) COLLATE pg_catalog."default" NOT NULL,
    field_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    radet_value text COLLATE pg_catalog."default",
    care_card_value text COLLATE pg_catalog."default",
    status character varying(50) COLLATE pg_catalog."default" NOT NULL,
    logical_error_type character varying(100) COLLATE pg_catalog."default",
    logical_error_description text COLLATE pg_catalog."default",
    validation_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT validation_results_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.clinical_events
    ADD CONSTRAINT clinical_events_patient_id_fkey FOREIGN KEY (patient_id)
    REFERENCES public.radet_records (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_events_patient
    ON public.clinical_events(patient_id);


ALTER TABLE IF EXISTS public.correction_logs
    ADD CONSTRAINT correction_logs_patient_id_fkey FOREIGN KEY (patient_id)
    REFERENCES public.radet_records (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.correction_logs
    ADD CONSTRAINT correction_logs_supervisor_id_fkey FOREIGN KEY (supervisor_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.correction_logs
    ADD CONSTRAINT correction_logs_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.radet_records
    ADD CONSTRAINT radet_records_cycle_id_fkey FOREIGN KEY (cycle_id)
    REFERENCES public.validation_cycles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_radet_cycle
    ON public.radet_records(cycle_id);


ALTER TABLE IF EXISTS public.validation_results
    ADD CONSTRAINT validation_results_cycle_id_fkey FOREIGN KEY (cycle_id)
    REFERENCES public.validation_cycles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_results_cycle
    ON public.validation_results(cycle_id);


ALTER TABLE IF EXISTS public.validation_results
    ADD CONSTRAINT validation_results_patient_id_fkey FOREIGN KEY (patient_id)
    REFERENCES public.radet_records (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_results_patient
    ON public.validation_results(patient_id);


ALTER TABLE IF EXISTS public.validation_results
    ADD CONSTRAINT validation_results_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;